### ISSUE TITLE
typeDefs and typePaths aren't merged properly

### ISSUE THREAD

**Issue by oney** [nestjs/graphql#1111]
## I'm submitting a...

<pre><code>
[x] Bug report
</code></pre>

## Current behavior

```js
GraphQLModule.forRoot({
  typeDefs: `
type Query {
  hello: String
}
`,
  typePaths: ['./**/*.graphql'],
})
```
```
UnhandledPromiseRejectionWarning: Error: There can be only one type named "Query".
    at assertValidSDL (/Users/one/repos/verbo/verbo-demo/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (/Users/one/repos/verbo/verbo-demo/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at buildSchemaFromTypeDefinitions (/Users/one/repos/verbo/verbo-demo/node_modules/@graphql-tools/schema/index.cjs.js:203:26)
    at Object.makeExecutableSchema (/Users/one/repos/verbo/verbo-demo/node_modules/@graphql-tools/schema/index.cjs.js:705:18)
```

## Expected behavior

typeDefs that includes`type Query` declaration should be merged with typePaths like there are multiple graphql files in typePaths declaring `type Query`.

## Minimal reproduction of the problem with instructions

See above codes.
## Environment

<pre><code>
Nest version: 7.0.0

 
For Tooling issues:
- Node version: v12.14.0
- Platform:  Mac
</code></pre>

I think we should replace [this line](https://github.com/nestjs/graphql/blob/master/lib/graphql.module.ts#L135) to be something [like here](https://github.com/nestjs/graphql/blob/master/lib/graphql-types.loader.ts#L21)

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by brianschardt** [comment]
Yea they dont merge the schemas they just concat the strings. I will be forking this repo
