### ISSUE TITLE
Union type cannot be used as argument

### ISSUE THREAD

**Issue by muradm** [nestjs/graphql#1247]
## I'm submitting a...
<pre><code>[ ] Regression
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Union type cannot be used as argument. Throws below exception on startup:
```
UnhandledPromiseRejectionWarning: Error: Cannot determine a GraphQL input type for the "command". Make sure your class is decorated with an appropriate decorator.
    at InputTypeFactory.create (/home/muradm/devel/oss/nestjs-graphql-union-arg-problem/node_modules/@nestjs/graphql/dist/schema-builder/factories/input-type.factory.js:19:23)
    at /home/muradm/devel/oss/nestjs-graphql-union-arg-problem/node_modules/@nestjs/graphql/dist/schema-builder/factories/args.factory.js:20:49
    at Array.forEach (<anonymous>)
    at ArgsFactory.create (/home/muradm/devel/oss/nestjs-graphql-union-arg-problem/node_modules/@nestjs/graphql/dist/schema-builder/factories/args.factory.js:16:14)
    at /home/muradm/devel/oss/nestjs-graphql-union-arg-problem/node_modules/@nestjs/graphql/dist/schema-builder/factories/root-type.factory.js:40:40
    at Array.forEach (<anonymous>)
    at RootTypeFactory.generateFields (/home/muradm/devel/oss/nestjs-graphql-union-arg-problem/node_modules/@nestjs/graphql/dist/schema-builder/factories/root-type.factory.js:34:14)
    at fieldsFactory (/home/muradm/devel/oss/nestjs-graphql-union-arg-problem/node_modules/@nestjs/graphql/dist/schema-builder/factories/root-type.factory.js:18:101)
    at RootTypeFactory.create (/home/muradm/devel/oss/nestjs-graphql-union-arg-problem/node_modules/@nestjs/graphql/dist/schema-builder/factories/root-type.factory.js:27:21)
    at MutationTypeFactory.create (/home/muradm/devel/oss/nestjs-graphql-union-arg-problem/node_modules/@nestjs/graphql/dist/schema-builder/factories/mutation-type.factory.js:15:37)
```

## Expected behavior
Union type to be used as argumnet.

## Minimal reproduction of the problem with instructions
Run from [this repository](https://github.com/muradm/nestjs-graphql-union-arg-problem).

## What is the motivation / use case for changing the behavior?
Union type as argument.

## Environment
Recent using quick start instructions as of this issue submission.

**Comment by kamilmysliwiec** [comment]
There's no such thing as input union (at least for now) https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md
