### ISSUE TITLE
/node_modules/@nestjs/graphql/dist/schema-builder/storages/type-metadata.storage.js:187

### ISSUE THREAD

**Issue by simayi0322** [nestjs/graphql#1309]
/Users/choeseolbeom/Desktop/playground/number-eats-backend/node_modules/@nestjs/graphql/dist/schema-builder/storages/type-metadata.storage.js:187
            if (!item.properties) {
                      ^

TypeError: Cannot read property 'properties' of undefined
    at /Users/choeseolbeom/Desktop/playground/number-eats-backend/node_modules/@nestjs/graphql/dist/schema-builder/storages/type-metadata.storage.js:187:23
    at Array.forEach (<anonymous>)
    at TypeMetadataStorageHost.compileClassMetadata (/Users/choeseolbeom/Desktop/playground/number-eats-backend/node_modules/@nestjs/graphql/dist/schema-builder/storages/type-metadata.storage.js:185:18)
    at Object.getFieldsAndDecoratorForType (/Users/choeseolbeom/Desktop/playground/number-eats-backend/node_modules/@nestjs/graphql/dist/schema-builder/utils/get-fields-and-decorator.util.js:22:49)
    at Object.PickType (/Users/choeseolbeom/Desktop/playground/number-eats-backend/node_modules/@nestjs/graphql/dist/type-helpers/pick-type.helper.js:9:74)
    at Object.<anonymous> (/Users/choeseolbeom/Desktop/playground/number-eats-backend/dist/src/users/dto/create-account.dto.js:35:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)

my package.json

"dependencies": {
    "@nestjs/common": "^7.5.1",
    "@nestjs/config": "^0.6.1",
    "@nestjs/core": "^7.5.1",
    "@nestjs/graphql": "^7.9.3",
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/typeorm": "^7.1.5",
    "apollo-server-express": "^2.19.1",
    "bcrypt": "^5.0.0",
    "class-validator": "^0.12.2",
    "cross-env": "^7.0.3",
    "graphql": "^15.4.0",
    "graphql-tools": "^7.0.2",
    "joi": "^17.3.0",
    "pg": "^8.5.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.3",
    "typeorm": "^0.2.29"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.5.1",
    "@nestjs/schematics": "^7.1.3",
    "@nestjs/testing": "^7.5.1",
    "@types/bcrypt": "^3.0.0",
    "@types/express": "^4.17.8",
    "@types/jest": "^26.0.15",
    "@types/node": "^14.14.6",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.6.1",
    "@typescript-eslint/parser": "^4.6.1",
    "eslint": "^7.12.1",
    "eslint-config-prettier": "7.0.0",
    "eslint-plugin-prettier": "^3.1.4",
    "jest": "^26.6.3",
    "prettier": "^2.1.2",
    "supertest": "^6.0.0",
    "ts-jest": "^26.4.3",
    "ts-loader": "^8.0.8",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.0.5"
  },

**Comment by kamilmysliwiec** [comment]
Fixed in 7.9.4.
