### ISSUE TITLE
Hot Module Reload not working with GraphQL/Apollo Server

### ISSUE THREAD

**Issue by phiggins** [nestjs/graphql#1707]
### Current behavior

Followup to:
* https://github.com/nestjs/nest/issues/7840
* https://github.com/apollographql/apollo-server/issues/5613

Following the [NestJS Hot Reload guide](https://docs.nestjs.com/recipes/hot-reload) does not work with Apollo. After making an update to a GraphQL resolver, the server builds again, and other non-GraphQL controllers/endpoints work, but for a variable time period (several seconds to several minutes) all GraphQL queries/mutations return the error:

```
Error: Cannot execute GraphQL operations after the server has stopped.
  at ApolloServer.<anonymous> (/Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:306:31)
  at Generator.next (<anonymous>)
  at /Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:8:71
  at new Promise (<anonymous>)
  at __awaiter (/Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:4:12)
  at ApolloServer.ensureStarted (/Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:283:16)
  at ApolloServer.<anonymous> (/Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:661:83)
  at Generator.next (<anonymous>)
  at /Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:8:71
  at new Promise (<anonymous>)
```

This appears to be thrown by Apollo Server when the server has stopped. My guess is that the internal Apollo Server
has been stopped by the reload process, but is taking a long time to restart for some reason.

While the linked repro does reproduce the issue, it seems to fix itself after a relatively short period of time. Our
(much larger) production Nest.js app takes much longer, on the order of 15-20 minutes.

Even catching this error in HMR mode and displaying something like "Apollo Server is restarting" would be helpful,
but best of course would be fixing the responsiveness of the hot-reloaded Apollo Server.

### Input Code

See minimal repro here: https://github.com/phiggins/hotreload-repro

### Expected behavior

In order for HMR to be useful in dev mode, the time between start of rebuild to a usable server must be
less than the time it would take to manually stop then restart the server.

### Environment

```
Nest version: 8.0.6

 
For Tooling issues:
- Node version: v16.0.0  
- Platform:  Mac Catalina (10.15.7) 

Others:

apollo-server-express/apollo-server-core 2.25.2
npm 7.10.0
also repros on yarn berry v3.0.0
```

/cc @davidgoli

**Comment by isaacpz** [comment]
Running into this same problem. I'll add that it seems like opening a new incognito tab for the playground fixes this problem for me, which is pretty odd.

**Comment by david-golightly-leapyear** [comment]
Issue at `apollo-server`: https://github.com/apollographql/apollo-server/issues/5613

**Comment by gterras** [comment]
Any news on this issue? It's a bit of a pain to work with graphql right now.

**Comment by vytautas-pranskunas-** [comment]
watching

**Comment by vytautas-pranskunas-** [comment]
@kamilmysliwiec both teams pointing to one another. However i can confirm that webpack hot module replacement works fine without nestjs. It would be super cool if you can take closer look to this because it is very annoying development when app is runing but graphql is not.

**Comment by jedashford** [comment]
We're evaluating a move to nestjs from plain node and I don't think we could move our team to this if we need to restart dev server between each change :( Anyone find a work around or are you just manually restarting the service between changes?

**Comment by gterras** [comment]
> We're evaluating a move to nestjs from plain node and I don't think we could move our team to this if we need to restart dev server between each change :( Anyone find a work around or are you just manually restarting the service between changes?

As far as I know this issue is fixed.

**Comment by kdawgwilk** [comment]
I do see the original issue sometimes but not very frequent

**Comment by simplenotezy** [comment]
As[ per the documentation](https://docs.nestjs.com/recipes/hot-reload):

>Note that webpack won't automatically copy your assets (e.g. graphql files) to the dist folder. Similarly, webpack is not compatible with glob static paths (e.g., the entities property in TypeOrmModule).

Is there some examples of getting hotreload to work with webpack and graphql?
