### ISSUE TITLE
Federated gateway requires explicit subscriptions setting to be false

### ISSUE THREAD

**Issue by gfviegas** [nestjs/graphql#1749]
Using 

```javascript
"@nestjs/common": "^8.0.6",
"@nestjs/config": "^1.0.1",
"@nestjs/core": "^8.0.6",
"@nestjs/graphql": "^9.0.4",
"@nestjs/mapped-types": "^1.0.0",
"@nestjs/platform-express": "^8.0.6",
"@apollo/gateway": "^0.41.0",
"graphql": "^15.5.3",
"@nestjs/cli": "^8.1.1",
"@nestjs/schematics": "^8.0.3",
"@nestjs/testing": "^8.0.6",
```

When I start a GraphQL Federated Gateway module just as the [example one](https://docs.nestjs.com/graphql/federation#federated-example-gateway) a exception is thrown in initialization:

```
(node:542) UnhandledPromiseRejectionWarning: Error: Subscriptions are not yet compatible with the gateway. Set `subscriptions: false` in Apollo Server's constructor to explicitly disable subscriptions (which are on by default) and allow for gateway functionality.
    at new ApolloServerBase (/code/node_modules/apollo-server-express/node_modules/apollo-server-core/src/ApolloServer.ts:313:13)
    at new ApolloServer (/code/node_modules/apollo-server-express/src/ApolloServer.ts:88:5)
    at GraphQLGatewayModule.registerExpress (/code/node_modules/@nestjs/graphql/dist/federation/graphql-gateway.module.js:115:30)
    at GraphQLGatewayModule.registerGqlServer (/code/node_modules/@nestjs/graphql/dist/federation/graphql-gateway.module.js:101:24)
    at GraphQLGatewayModule.onModuleInit (/code/node_modules/@nestjs/graphql/dist/federation/graphql-gateway.module.js:84:20)
    at Object.callModuleInitHook (/code/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:35)
    at NestApplication.callInitHook (/code/node_modules/@nestjs/core/nest-application-context.js:169:13)
    at NestApplication.init (/code/node_modules/@nestjs/core/nest-application.js:97:9)
    at NestApplication.listen (/code/node_modules/@nestjs/core/nest-application.js:156:33)
    at bootstrap (/code/src/main.ts:21:3)
```

It seems like it is now required to explicit set the subscriptions option to false in Apollo Server's settings.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/1750
