### ISSUE TITLE
Cannot find module @apollo/subgraph

### ISSUE THREAD

**Issue by openscript** [nestjs/graphql#1814]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

9.0.6 -> 9.1.0

### Describe the regression

Package `@apollo/subgraph` is missing.

```
$ ts-node ./node_modules/typeorm/cli schema:sync -f src/cli/loader.ts
Loading env from /workspace/environment/dev.env
query: SELECT * FROM current_schema()
Error during schema synchronization:
Error: Cannot find module '@apollo/subgraph/dist/schemaExtensions'
Require stack:
- /workspace/node_modules/@nestjs/graphql/dist/utils/transform-schema.util.js
- /workspace/node_modules/@nestjs/graphql/dist/federation/graphql-federation.factory.js
- /workspace/node_modules/@nestjs/graphql/dist/federation/index.js
- /workspace/node_modules/@nestjs/graphql/dist/index.js
- /workspace/node_modules/@nestjs/graphql/index.js
- /workspace/dist/offer/entity/offer-state.entity.js
- /workspace/dist/offer/subscriber/offer.subscriber.js
- /workspace/node_modules/typeorm/util/DirectoryExportedClassesLoader.js
- /workspace/node_modules/typeorm/connection/ConnectionMetadataBuilder.js
- /workspace/node_modules/typeorm/connection/Connection.js
- /workspace/node_modules/typeorm/connection/ConnectionManager.js
- /workspace/node_modules/typeorm/globals.js
- /workspace/node_modules/typeorm/commands/SchemaSyncCommand.js
- /workspace/node_modules/typeorm/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/workspace/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/workspace/node_modules/@nestjs/graphql/dist/utils/transform-schema.util.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspace/node_modules/@nestjs/graphql/dist/utils/transform-schema.util.js',
    '/workspace/node_modules/@nestjs/graphql/dist/federation/graphql-federation.factory.js',
    '/workspace/node_modules/@nestjs/graphql/dist/federation/index.js',
    '/workspace/node_modules/@nestjs/graphql/dist/index.js',
    '/workspace/node_modules/@nestjs/graphql/index.js',
    '/workspace/dist/offer/entity/offer-state.entity.js',
    '/workspace/dist/offer/subscriber/offer.subscriber.js',
    '/workspace/node_modules/typeorm/util/DirectoryExportedClassesLoader.js',
    '/workspace/node_modules/typeorm/connection/ConnectionMetadataBuilder.js',
    '/workspace/node_modules/typeorm/connection/Connection.js',
    '/workspace/node_modules/typeorm/connection/ConnectionManager.js',
    '/workspace/node_modules/typeorm/globals.js',
    '/workspace/node_modules/typeorm/commands/SchemaSyncCommand.js',
    '/workspace/node_modules/typeorm/cli.js'
  ]
}
error Command failed with exit code 1.
```

### Minimum reproduction code

Start a nest project using the `graphql` package.

### Expected behavior

Either that the package brings `@apollo/subgraph` as a dependency along or some hint in the README.md and migration guide.

### Other

To fix the issue the package `@apollo/subgraph` can be added as a dependency.

Thank you for your work <3

**Comment by jp928** [comment]
Same here + 1
