### ISSUE TITLE
@nestjs/graphql 9.1.1 no longer compatible with latest @apollo/subgraph and @apollo/federation

### ISSUE THREAD

**Issue by bokjo** [nestjs/graphql#1891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello Nest,

I've started updating my service to the latest possible versions and node version as well for my packages. 
Upon seeing the changes for the Apollo Feredration split into the new Subgraph package and NestJS documentation suggesting it as well, I've added @appllo/subgraph ^0.1.5 which is the latest one and the service no longer starts

```sh
npm run start

> example-gql-service@0.0.1 start
> nest start

[Nest] 61498  - 11/24/2021, 9:10:20 AM     LOG [NestFactory] Starting Nest application...
[Nest] 61498  - 11/24/2021, 9:10:20 AM     LOG [InstanceLoader] AppModule dependencies initialized +116ms
[Nest] 61498  - 11/24/2021, 9:10:20 AM     LOG [InstanceLoader] HttpModule dependencies initialized +1ms
[Nest] 61498  - 11/24/2021, 9:10:20 AM     LOG [InstanceLoader] TerminusModule dependencies initialized +0ms
[Nest] 61498  - 11/24/2021, 9:10:20 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 61498  - 11/24/2021, 9:10:20 AM     LOG [InstanceLoader] LoggerModule dependencies initialized +0ms
[Nest] 61498  - 11/24/2021, 9:10:20 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 61498  - 11/24/2021, 9:10:20 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 61498  - 11/24/2021, 9:10:20 AM     LOG [InstanceLoader] HealthModule dependencies initialized +1ms
[Nest] 61498  - 11/24/2021, 9:10:21 AM     LOG [InstanceLoader] CacheModule dependencies initialized +74ms
[Nest] 61498  - 11/24/2021, 9:10:21 AM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +1ms
[Nest] 61498  - 11/24/2021, 9:10:21 AM     LOG [InstanceLoader] GraphQLFederationModule dependencies initialized +67ms
[Nest] 61498  - 11/24/2021, 9:10:21 AM     LOG [InstanceLoader] AuthModule dependencies initialized +0ms
{"level":30,"time":1637741421083,"pid":61498,"hostname":"cheMBP.local","context":"RoutesResolver","msg":"HealthController {/health}:"}
{"level":30,"time":1637741421086,"pid":61498,"hostname":"cheMBP.local","context":"RouterExplorer","msg":"Mapped {/health, GET} route"}
{"level":30,"time":1637741421086,"pid":61498,"hostname":"cheMBP.local","context":"RouterExplorer","msg":"Mapped {/health/readiness, GET} route"}
{"level":30,"time":1637741421086,"pid":61498,"hostname":"cheMBP.local","context":"RouterExplorer","msg":"Mapped {/health/liveness, GET} route"}
{"level":30,"time":1637741421086,"pid":61498,"hostname":"cheMBP.local","context":"RouterExplorer","msg":"Mapped {/health/memory, GET} route"}
{"level":30,"time":1637741421086,"pid":61498,"hostname":"cheMBP.local","context":"RouterExplorer","msg":"Mapped {/health/cpu, GET} route"}

/Users/bojanche/dev/libraries/gql-microservice-template/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:46
                    ...this.loadFederationDirectives(),
                            ^
TypeError: this.loadFederationDirectives is not a function or its return value is not iterable
    at GraphQLSchemaBuilder.buildFederatedSchema (/Users/bojanche/dev/libraries/gql-microservice-template/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:46:29)
    at GraphQLFederationFactory.generateSchema (/Users/bojanche/dev/libraries/gql-microservice-template/node_modules/@nestjs/graphql/dist/federation/graphql-federation.factory.js:59:65)
    at GraphQLFederationFactory.mergeOptions (/Users/bojanche/dev/libraries/gql-microservice-template/node_modules/@nestjs/graphql/dist/federation/graphql-federation.factory.js:30:33)
    at GraphQLFederationModule.onModuleInit (/Users/bojanche/dev/libraries/gql-microservice-template/node_modules/@nestjs/graphql/dist/federation/graphql-federation.module.js:92:67)
    at Object.callModuleInitHook (/Users/bojanche/dev/libraries/gql-microservice-template/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at NestApplication.callInitHook (/Users/bojanche/dev/libraries/gql-microservice-template/node_modules/@nestjs/core/nest-application-context.js:169:13)
    at NestApplication.init (/Users/bojanche/dev/libraries/gql-microservice-template/node_modules/@nestjs/core/nest-application.js:97:9)
    at NestApplication.listen (/Users/bojanche/dev/libraries/gql-microservice-template/node_modules/@nestjs/core/nest-application.js:156:33)
    at bootstrap (/Users/bojanche/dev/libraries/gql-microservice-template/src/main.ts:18:3)
```

Did some investigation as well:

@nestjs/graphql@9.1.1 federation graphql-schema.builder => https://github.com/nestjs/graphql/blob/a29470f87f77c42f5174ffdc251ec9cae73d577c/lib/graphql-schema.builder.ts#L118

expects `federationDirectives` to be exported, but unfortunately in @apollo/subgraph@0.1.5 this field changed name to `directivesWithNoDefinitionNeeded` => https://github.com/apollographql/federation/blob/caa378c31a136423f463bb1b5b83064671f0be7a/subgraph-js/src/directives.ts#L104

This causes `loadFederationDirectives()` to return `undefined` and then throw `TypeError`.

Installing **@apollo/subgraph@0.1.4** explicitly solves this issue because `federationDirectives` is still there, please take a look for the further versions

I'm also seeing open PR #1813 that will need alignment as well 

https://github.com/nestjs/graphql/pull/1813/files#diff-7f41c325d7df3fdc5090dadceda4b6b53f136677010378d756421f2e49389e50R119

### Minimum reproduction code

/

### Steps to reproduce

/

### Expected behavior

The service should start and not throw an TypeError exception 

### Package version

9.1.1

### Graphql version

`graphql`:  15.5.3
`apollo-server-express`: 3.3.0

### NestJS version

8.2.3

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Fixed in 9.1.2
