### ISSUE TITLE
GraphQLError: Syntax Error with registerEnumType function exported from @nestjs/graphql

### ISSUE THREAD

**Issue by GreatLaboratory** [nestjs/graphql#2014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Please see this line below (https://github.com/GreatLaboratory/nestjs-graphql-example/blob/main/src/domain/posts/models/post.model.ts#L39)

when i try to run the nestjs app, app is not running. Just throw the error below

```
/Users/greatlaboratory/Desktop/projects/nestjs-graphql-example/node_modules/graphql/error/syntaxError.js:15
  return new _GraphQLError.GraphQLError("Syntax Error: ".concat(description), undefined, source, [position]);
         ^
GraphQLError: Syntax Error: Invalid character within String: "\u001d".
    at syntaxError (/Users/greatlaboratory/Desktop/projects/nestjs-graphql-example/node_modules/graphql/error/syntaxError.js:15:10)
    at readBlockString (/Users/greatlaboratory/Desktop/projects/nestjs-graphql-example/node_modules/graphql/language/lexer.js:602:42)
    at readToken (/Users/greatlaboratory/Desktop/projects/nestjs-graphql-example/node_modules/graphql/language/lexer.js:222:18)
    at Lexer.lookahead (/Users/greatlaboratory/Desktop/projects/nestjs-graphql-example/node_modules/graphql/language/lexer.js:75:108)
    at Lexer.advance (/Users/greatlaboratory/Desktop/projects/nestjs-graphql-example/node_modules/graphql/language/lexer.js:58:35)
    at Parser.expectOptionalToken (/Users/greatlaboratory/Desktop/projects/nestjs-graphql-example/node_modules/graphql/language/parser.js:1425:19)
    at Parser.optionalMany (/Users/greatlaboratory/Desktop/projects/nestjs-graphql-example/node_modules/graphql/language/parser.js:1504:22)
    at Parser.parseFieldsDefinition (/Users/greatlaboratory/Desktop/projects/nestjs-graphql-example/node_modules/graphql/language/parser.js:868:17)
    at Parser.parseObjectTypeDefinition (/Users/greatlaboratory/Desktop/projects/nestjs-graphql-example/node_modules/graphql/language/parser.js:812:23)
    at Parser.parseTypeSystemDefinition (/Users/greatlaboratory/Desktop/projects/nestjs-graphql-example/node_modules/graphql/language/parser.js:708:23)
```

Although app is not running, `schema.gql` dsl file is made perfectly..
```
"""post cover color"""
enum PostColor {
  BLUE @deprecated(reason: "feel so blue")

  """my favorite color"""
  GREEN

  """default color"""
  RED
}
```

### Minimum reproduction code

https://github.com/GreatLaboratory/nestjs-graphql-example

### Steps to reproduce

1. `npm i`
2. `npm start`

### Expected behavior

In this situation, app is not running not at all.
App should run...

### Package version

9.1.2

### Graphql version

`graphql`: 15.8.0
`apollo-server-express`: 3.6.3
`apollo-server-fastify`: 

### NestJS version

8.0.0

### Node.js version

16.5.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jaypea** [comment]
@GreatLaboratory have you tried deleting the non-ascii character at the end of the PostColor enum Description?
