### ISSUE TITLE
Regression: Support for returning GraphQLObjectType from resolveType was removed, please return type name instead.

### ISSUE THREAD

**Issue by Shinigami92** [nestjs/graphql#2024]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

9.1.2 -> 10.0.2

### Describe the regression

Until now, no one answered at discord https://discord.com/channels/520622812742811698/943779132335063101, so I'm opening an issue.

I'm getting following error when updating to `@nestjs/graphql` v10

> Support for returning GraphQLObjectType from resolveType was removed in graphql-js@16.0.0 please return type name instead.

![image](https://user-images.githubusercontent.com/7195563/154641084-a31f931e-0d8e-40f1-8d04-16482eef9ad2.png)

![image](https://user-images.githubusercontent.com/7195563/154641106-836dcb5c-7968-41d8-a0aa-be14c09fd385.png)

So with my previous (using v9) setup everything worked!

### Minimum reproduction code

```ts
@InterfaceType({ isAbstract: true })
export abstract class Node { ...

@InterfaceType({ implements: () => [Node] })
export class Subject extends Node { ...

@ObjectType({ implements: () => [Subject, Node] })
export class Person extends Subject {
```

### Expected behavior

Works as in v9 or have a documented workaround

### Other

In the reproduction I have a stack of extending classes.

Person extends Subject
Subject extends Node

Person and Subject are real non abstract classes
Node is an abstract class

I have resolvers for getting all persons (paginated) and getting all subjects (also paginated)

When I use `ObjectType` ob Subject I get following error (with v9 and v10):

```node
/home/project/api-gateway/node_modules/.pnpm/graphql@16.3.0/node_modules/graphql/type/definition.js:500
  return typeof thunk === 'function' ? thunk() : thunk;
                                       ^
TypeError: Cannot read properties of undefined (reading 'type')
    at /home/project/api-gateway/node_modules/.pnpm/@nestjs+graphql@10.0.2_12137c47a8c555a5989e659622fd536f/node_modules/@nestjs/graphql/dist/schema-builder/factories/object-type-definition.factory.js:55:173
    at Array.map (<anonymous>)
    at /home/project/api-gateway/node_modules/.pnpm/@nestjs+graphql@10.0.2_12137c47a8c555a5989e659622fd536f/node_modules/@nestjs/graphql/dist/schema-builder/factories/object-type-definition.factory.js:55:105
    at resolveReadonlyArrayThunk (/home/project/api-gateway/node_modules/.pnpm/graphql@16.3.0/node_modules/graphql/type/definition.js:500:40)
    at defineInterfaces (/home/project/api-gateway/node_modules/.pnpm/graphql@16.3.0/node_modules/graphql/type/definition.js:745:22)
    at GraphQLObjectType._interfaces (/home/project/api-gateway/node_modules/.pnpm/graphql@16.3.0/node_modules/graphql/type/definition.js:687:30)
    at GraphQLObjectType.getInterfaces (/home/project/api-gateway/node_modules/.pnpm/graphql@16.3.0/node_modules/graphql/type/definition.js:712:31)
    at collectReferencedTypes (/home/project/api-gateway/node_modules/.pnpm/graphql@16.3.0/node_modules/graphql/type/schema.js:383:45)
    at new GraphQLSchema (/home/project/api-gateway/node_modules/.pnpm/graphql@16.3.0/node_modules/graphql/type/schema.js:174:9)
    at GraphQLSchemaFactory.create (/home/project/api-gateway/node_modules/.pnpm/@nestjs+graphql@10.0.2_12137c47a8c555a5989e659622fd536f/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:39:24)
```

If you need more details, let me know

**Comment by arantespp** [comment]
@kamilmysliwiec would you mind sharing (link the PR) how did you solve this?

**Comment by csori99** [comment]
> @kamilmysliwiec, would you mind sharing (PR's link) how you solved this?

do you mind sharing how did u fix it? currently stuck on this in version 12
