### ISSUE TITLE
NestJS - GraphQL not working in my jest E2E "is not a function"

### ISSUE THREAD

**Issue by sebastien-abbal** [nestjs/graphql#2026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It's 3 days i am on this problem of E2E tests on my GraphQL application with NestJS + Apollo / Express.

When I am running my app with *serverless offline* or directly with my *main file*, it's working perfectly. I have my graph and all things I need :)

But, when I am running E2E tests with Jest, I received an error from the `await app.init()` inside the `beforeEach`.

After playing with the package.json and dependencies, the error change from `TypeError: (0 , schema_1.makeExecutableSchema) is not a function` to this error `TypeError: (0 , apollo_server_core_1.ApolloServerPluginLandingPageGraphQLPlayground) is not a function`

Someone have any idea please ? I am totally blocked ... :(

```
FAIL  src/__tests/graphql/common.e2e-spec.ts (6.779 s)
  ● GraphQL - CommonModule (e2e) › Query - Test › should return the welcome message (code: 200)

    TypeError: (0 , schema_1.makeExecutableSchema) is not a function

      15 |     app = moduleFixture.createNestApplication();
      16 |     // app.useGlobalPipes(new ValidationPipe());
    > 17 |     await app.init();
         |     ^
      18 |
      19 |     request = superRequest(app.getHttpServer());
      20 |   });

      at GraphQLFactory.mergeWithSchema (node_modules/@nestjs/graphql/dist/graphql.factory.js:30:72)
      at ApolloDriver.start (node_modules/@nestjs/apollo/dist/drivers/apollo.driver.js:19:25)
      at GraphQLModule.onModuleInit (node_modules/@nestjs/graphql/dist/graphql.module.js:103:9)
      at callModuleInitHook (node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
      at Proxy.callInitHook (node_modules/@nestjs/core/nest-application-context.js:179:13)
      at Proxy.init (node_modules/@nestjs/core/nest-application.js:96:9)
      at Object.<anonymous> (src/__tests/graphql/common.e2e-spec.ts:17:5)

____________________________________________________________________________

 FAIL  src/__tests/graphql/common.e2e-spec.ts (6.809 s)
  GraphQL - CommonModule (e2e)
    Query - Test
      ✕ should return the welcome message (code: 200) (415 ms)

  ● GraphQL - CommonModule (e2e) › Query - Test › should return the welcome message (code: 200)

    TypeError: (0 , apollo_server_core_1.ApolloServerPluginLandingPageGraphQLPlayground) is not a function

      15 |     app = moduleFixture.createNestApplication();
      16 |     app.useGlobalPipes(new ValidationPipe());
    > 17 |     await app.init();
         |     ^
      18 |
      19 |     request = superRequest(app.getHttpServer());
      20 |   });

      at ApolloDriver.mergeDefaultOptions (node_modules/@nestjs/apollo/dist/drivers/apollo-base.driver.js:50:93)
      at GraphQLModule.onModuleInit (node_modules/@nestjs/graphql/dist/graphql.module.js:99:52)
      at callModuleInitHook (node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:35)
      at Proxy.callInitHook (node_modules/@nestjs/core/nest-application-context.js:179:13)
      at Proxy.init (node_modules/@nestjs/core/nest-application.js:96:9)
      at Object.<anonymous> (src/__tests/graphql/common.e2e-spec.ts:17:5)
```

**package.json**
```json
"dependencies": {
    "@nestjs/apollo": "^10.0.2",
    "@nestjs/common": "^8.3.0",
    "@nestjs/core": "^8.3.0",
    "@nestjs/graphql": "^10.0.2",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/passport": "^8.2.0",
    "@nestjs/platform-express": "^8.3.0",
    "graphql": "^16.3.0",
    "graphql-query-complexity": "^0.11.0",
    "apollo-server-express": "^3.6.3",
    "apollo-server-plugin-base": "^3.5.1",
    ...
},
"devDependencies": {
    "jest": "^27.5.1",
    "prisma-nestjs-graphql": "^14.6.1",
    "supertest": "^6.2.2",
    "ts-jest": "^27.1.3",
    ...
}
```

**jest.config.ts**
```typescript
module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  testEnvironment: 'node',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  testRegex: '.(spec|e2e-spec).ts$',
  moduleNameMapper: {
    '^@features/(.*)': '<rootDir>/src/features/$1',
    '^@tests/(.*)': '<rootDir>/src/__tests/$1',
    '^@graphql': '<rootDir>/src/@graphql/generated',
    '^@types': '<rootDir>/src/@types',
    '^@utils': '<rootDir>/src/utils',
    '^@config': '<rootDir>/src/config',
  },
  testPathIgnorePatterns: [
    '<rootDir>/dist/',
    '<rootDir>/prisma/',
    '<rootDir>/bin/',
    '<rootDir>/node_modules/',
    '<rootDir>/.github/',
  ],
};
```

**graphql.e2e-spec.ts**
```typescript
import { GraphQLModule } from '@features/graphql/graphql.module';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import superRequest, { SuperTest, Test as TestItem } from 'supertest';

describe('GraphQL - CommonModule (e2e)', () => {
  let app: INestApplication;
  let request: SuperTest<TestItem>;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [GraphQLModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    app.useGlobalPipes(new ValidationPipe());
    await app.init();

    request = superRequest(app.getHttpServer());
  });

  describe('Query - Test', () => {
    it('should return the welcome message (code: 200)', async () => {
      return request
        .post('/graphql')
        .send({
          query: `
            query {
              test {
                __typename
              }
            }`,
        })
        .then((res) => {
          expect(res.status).toBe(200);
        });
    });
  });
});
```

**graphql.module.ts**
```typescript
import { config } from '@config';
import { AppService } from '@features/app.service';
import { GraphQLAuthModule } from '@features/graphql/auth/auth.module';
import { CommonModule } from '@features/graphql/common/common.module';
import { UserModule } from '@features/graphql/user/user.module';
import { GraphQLComplexityPlugin } from '@features/graphql/_plugins';
import { ApolloDriver, ApolloDriverConfig } from '@nestjs/apollo';
import { Module } from '@nestjs/common';
import { GraphQLModule as NESTJSGraphQLModule } from '@nestjs/graphql';
import { join } from 'path';

@Module({
  imports: [
    GraphQLAuthModule,
    NESTJSGraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      autoSchemaFile: join(process.cwd(), 'src/@graphql/schema.gql'),
      sortSchema: true,
      debug: config.graphql.isDebugEnabled,
      introspection: true,
      playground: config.graphql.isPlaygroundEnabled
        ? {
            settings: { 'schema.polling.enable': false },
          }
        : false,
    }),
    UserModule,
    CommonModule,
  ],
  providers: [AppService, GraphQLComplexityPlugin],
})
export class GraphQLModule {
  constructor(private readonly appService: AppService) {
    if (!this.appService.checkEnv()) process.exit();
  }
}
```

### Minimum reproduction code

https://stackoverflow.com/questions/71175141/nestjs-graphql-not-working-in-my-jest-e2e-is-not-a-function

### Steps to reproduce

$ jest

### Expected behavior

Tests must works but nothing happens ...

### Package version

10.0.2

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### NestJS version

8.3.0

### Node.js version

17.4.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

If you want an access to the repository, i can give you in PM or on discord with pleasure but not in public :)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
