### ISSUE TITLE
Missing "driver" option

### ISSUE THREAD

**Issue by TrejGun** [nestjs/graphql#2061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

this is in the extension of closed https://github.com/nestjs/graphql/issues/2031

This is what I have on startup with new GQL setup

```
[Nest] 38772  - 03/05/2022, 8:51:06 AM   ERROR [GraphQLModule] Missing "driver" option. In the latest version of "@nestjs/graphql" package (v10) a new required configuration property called "driver" has been introduced. Check out the official documentation for more details on how to migrate (https://docs.nestjs.com/graphql/migration-guide). Example:

GraphQLModule.forRoot<ApolloDriverConfig>({
  driver: ApolloDriver,
})
~/nestjs-validation/node_modules/@nestjs/graphql/dist/graphql.module.js:120
            throw new Error(errorMessage);
            ^

Error: Missing "driver" option. In the latest version of "@nestjs/graphql" package (v10) a new required configuration property called "driver" has been introduced. Check out the official documentation for more details on how to migrate (https://docs.nestjs.com/graphql/migration-guide). Example:

GraphQLModule.forRoot<ApolloDriverConfig>({
  driver: ApolloDriver,
})
    at Function.assertDriver (~/nestjs-validation/node_modules/@nestjs/graphql/dist/graphql.module.js:120:19)
    at Function.forRootAsync (~/nestjs-validation/node_modules/@nestjs/graphql/dist/graphql.module.js:51:14)
    at Object.<anonymous> (~/nestjs-validation/dist/app.module.js:34:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (~/nestjs-validation/dist/index.js:6:22)
```

### Minimum reproduction code

https://github.com/GemunIon/nestjs-validation

### Steps to reproduce

npm i
npm start

### Expected behavior

no error on startup

### Package version

10.0.6

### Graphql version

"graphql": "16.3.0",
"apollo-server-express": "3.6.3",

### NestJS version

8.4.0

### Node.js version

v16.7.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
The `driver` needs to be a top level config, not something returned by the factory, [as shown in the docs](https://docs.nestjs.com/graphql/quick-start#async-configuration)

```ts
GraphQLModule.forRootAsync<ApolloDriverAsyncConfig>({
  driver: ApolloDriver,
  imports: [ConfigModule],
  useFactory: async (configService: ConfigService) => ({
    typePaths: configService.getString('GRAPHQL_TYPE_PATHS'),
  }),
  inject: [ConfigService],
}),
```

**Comment by TrejGun** [comment]
@jmcdo29 thanks
