### ISSUE TITLE
Nest can't resolve dependencies of the ApolloDriver

### ISSUE THREAD

**Issue by Colt45s** [nestjs/graphql#2269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to build a GraphQL server in Nest.js using Turborepo.
I get the following error.

```
backend:dev: [19:38:21] Found 0 errors. Watching for file changes.
backend:dev: 
backend:dev: [Nest] 301573  - 2022/06/29 19:38:21     LOG [NestFactory] Starting Nest application...
backend:dev: [Nest] 301573  - 2022/06/29 19:38:21     LOG [InstanceLoader] AppModule dependencies initialized +26ms
backend:dev: [Nest] 301573  - 2022/06/29 19:38:21   ERROR [ExceptionHandler] Nest can't resolve dependencies of the ApolloDriver (?). Please make sure that the argument ModulesContainer at index [0] is available in the GraphQLModule context.
backend:dev: 
backend:dev: Potential solutions:
backend:dev: - If ModulesContainer is a provider, is it part of the current GraphQLModule?
backend:dev: - If ModulesContainer is exported from a separate @Module, is that module imported within GraphQLModule?
backend:dev:   @Module({
backend:dev:     imports: [ /* the Module containing ModulesContainer */ ]
backend:dev:   })
backend:dev: 
backend:dev: Error: Nest can't resolve dependencies of the ApolloDriver (?). Please make sure that the argument ModulesContainer at index [0] is available in the GraphQLModule context.
backend:dev: 
backend:dev: Potential solutions:
backend:dev: - If ModulesContainer is a provider, is it part of the current GraphQLModule?
backend:dev: - If ModulesContainer is exported from a separate @Module, is that module imported within GraphQLModule?
backend:dev:   @Module({
backend:dev:     imports: [ /* the Module containing ModulesContainer */ ]
backend:dev:   })
backend:dev: 
backend:dev:     at Injector.lookupComponentInParentModules (/home/u/Projects/stack/apps/backend/node_modules/@nestjs/core/injector/injector.js:231:19)
backend:dev:     at Injector.resolveComponentInstance (/home/u/Projects/stack/apps/backend/node_modules/@nestjs/core/injector/injector.js:184:33)
backend:dev:     at resolveParam (/home/u/Projects/stack/apps/backend/node_modules/@nestjs/core/injector/injector.js:106:38)
backend:dev:     at async Promise.all (index 0)
backend:dev:     at Injector.resolveConstructorParams (/home/u/Projects/stack/apps/backend/node_modules/@nestjs/core/injector/injector.js:121:27)
backend:dev:     at Injector.loadInstance (/home/u/Projects/stack/apps/backend/node_modules/@nestjs/core/injector/injector.js:52:9)
backend:dev:     at Injector.loadProvider (/home/u/Projects/stack/apps/backend/node_modules/@nestjs/core/injector/injector.js:74:9)
backend:dev:     at async Promise.all (index 13)
backend:dev:     at InstanceLoader.createInstancesOfProviders (/home/u/Projects/stack/apps/backend/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
backend:dev:     at /home/u/Projects/stack/apps/backend/node_modules/@nestjs/core/injector/instance-loader.js:29:13
```

### Minimum reproduction code

https://github.com/Colt45s/stack

### Steps to reproduce

In the root directory

1. `yarn install`
2. `yarn dev`

### Expected behavior

Nest.js application should run.

### Package version

10.0.11

### Graphql version

`graphql`: "16.4.0"
`@nestjs/apollo`: "10.0.11"

### NestJS version

8.4.4

### Node.js version

16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
