### ISSUE TITLE
 CannotDetermineOutputTypeError: Cannot determine a GraphQL output type for the "sendingStatus"

### ISSUE THREAD

**Issue by philosofonusus** [nestjs/graphql#2356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Starting application in production and development mode returns me this:
```
/node_modules/@nestjs/graphql/dist/schema-builder/factories/output-type.factory.js:19
api              |                 throw new cannot_determine_output_type_error_1.CannotDetermineOutputTypeError(hostType);
api              |                       ^
api              | 
api              | CannotDetermineOutputTypeError: Cannot determine a GraphQL output type for the "sendingStatus". Make sure your class is decorated with an appropriate decorator.
api              |     at OutputTypeFactory.create (/node_modules/@nestjs/graphql/dist/schema-builder/factories/output-type.factory.js:19:23)
api              |     at /node_modules/@nestjs/graphql/dist/schema-builder/factories/object-type-definition.factory.js:81:53
api              |     at Array.forEach (<anonymous>)
api              |     at /node_modules/@nestjs/graphql/dist/schema-builder/factories/object-type-definition.factory.js:80:24
api              |     at resolveObjMapThunk (/node_modules/graphql/type/definition.js:504:40)
api              |     at defineFieldMap (/node_modules/graphql/type/definition.js:760:20)
api              |     at GraphQLObjectType._fields (/node_modules/graphql/type/definition.js:685:26)
api              |     at GraphQLObjectType.getFields (/node_modules/graphql/type/definition.js:704:27)
api              |     at collectReferencedTypes (/node_modules/graphql/type/schema.js:387:51)
api              |     at new GraphQLSchema (/node_modules/graphql/type/schema.js:174:9)
api              | 
api              | Node.js v18.8.0
```

### Minimum reproduction code

https://github.com/philosofonusus/THR

### Steps to reproduce

1. sudo docker-compose up --build

### Expected behavior

Application starts successfully

### Package version

10.0.8

### Graphql version

`graphql`: 16.3.0
`graphql-upload`: 13.0.0
`prisma-graphql-type-decimal`: 2.0.0

### NestJS version

8.4.2

### Node.js version

18.8.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by iamkhalidbashir** [comment]
Same issue with me on jest

**Comment by iamkhalidbashir** [comment]
I think for your case it might fix by using registerEnum... function for sendingStatus
