### ISSUE TITLE
@ResolveField that returns a Union type fails to compile

### ISSUE THREAD

**Issue by atrudeau-vitall** [nestjs/graphql#2395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to create a field resolver using @ResolveField that returns a Union type, I get the following error
```
(node:69505) UnhandledPromiseRejectionWarning: Error: Cannot determine a GraphQL input type nullfor the "getMembers". Make sure your class is decorated with an appropriate decorator.
    at InputTypeFactory.create (/Users/alex-vitall/Desktop/dev/nestjs-graphql-union-resolvefield/node_modules/@nestjs/graphql/dist/schema-builder/factories/input-type.factory.js:19:23)
    at /Users/alex-vitall/Desktop/dev/nestjs-graphql-union-resolvefield/node_modules/@nestjs/graphql/dist/schema-builder/factories/input-type-definition.factory.js:48:52
    at Array.forEach (<anonymous>)
    at /Users/alex-vitall/Desktop/dev/nestjs-graphql-union-resolvefield/node_modules/@nestjs/graphql/dist/schema-builder/factories/input-type-definition.factory.js:46:33
    at resolveObjMapThunk (/Users/alex-vitall/Desktop/dev/nestjs-graphql-union-resolvefield/node_modules/graphql/type/definition.js:504:40)
    at defineInputFieldMap (/Users/alex-vitall/Desktop/dev/nestjs-graphql-union-resolvefield/node_modules/graphql/type/definition.js:1313:20)
    at GraphQLInputObjectType.getFields (/Users/alex-vitall/Desktop/dev/nestjs-graphql-union-resolvefield/node_modules/graphql/type/definition.js:1276:27)
    at collectReferencedTypes (/Users/alex-vitall/Desktop/dev/nestjs-graphql-union-resolvefield/node_modules/graphql/type/schema.js:395:51)
    at new GraphQLSchema (/Users/alex-vitall/Desktop/dev/nestjs-graphql-union-resolvefield/node_modules/graphql/type/schema.js:174:9)
    at GraphQLSchemaFactory.create (/Users/alex-vitall/Desktop/dev/nestjs-graphql-union-resolvefield/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:40:24)
```
This is what my resolver looks like
```typescript
import { Parent, Query, ResolveField, Resolver } from "@nestjs/graphql";
import { MyUnion, Team } from "./team.model";
import { TeamService } from "./team.service";

@Resolver(() => Team)
export class TeamResolver {
  constructor(private readonly teamService: TeamService) {}

  @Query(() => [Team], { name: "teams", nullable: true })
  async getTeams() {
    return this.teamService.getAll();
  }

  @ResolveField("members", () => [MyUnion], { nullable: true })
  async getMembers(@Parent() team: Team) {
    await Promise.resolve(team.id);
    return [
      {
        id: 123,
        name: "Bobby Alice",
        birthday: new Date(),
      },
      {
        id: 456,
        name: "Eiffel Tower",
        address: "123 Easy St",
      },
    ];
  }
}
```
Where MyUnion is 
```ts
export const MyUnion = createUnionType({
  name: "MyUnion",
  types: () => [Person, Place] as const,
  resolveType: (member) => {
    if (member.birthday) {
      return Person;
    }
    if (member.address) {
      return Place;
    }
  },
});

```
`MyUnion` is `Person | Place`, and when I use Query instead of ResolveField (i.e. return MyUnion from a Query), everything compiles fine. Also, if I choose one of the types in the union (Person/Place) and use that instead of MyUnion, it also compiles fine.

### Minimum reproduction code

https://github.com/atrudeau-vitall/nestjs-graphql-union-resolvefield

### Steps to reproduce

1. `yarn`
2. `yarn start`
3. See error in console

### Expected behavior

I know that it's possible for GraphQL to return a Union type from a field resolver because I've done it in past projects (not done with nestjs however). 

My query looks like this
```gql
query MyQuery {
  getTeams {
    id
    name
    createdAt
    members {
      ...PersonFields
      ...PlaceFields
    }
  }
}

fragment PersonFields on Person {
  id
  name
  birthday
}

fragment PlaceFields on Place {
  id
  name
  address
}
```
So what should happen is that the field resolver should be able to return both Person and Place objects in the response body.

### Package version

10.1.1

### Graphql version

`graphql`: 16.3.0
`apollo-server-express`: 3.6.3
`apollo-server-fastify`: NA

### NestJS version

9.0.11

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
