### ISSUE TITLE
(node:9676) UnhandledPromiseRejectionWarning: Error: Generating schema error

### ISSUE THREAD

**Issue by keonsam** [nestjs/graphql#268]
Can't get the schema to generate

[0] (node:9676) UnhandledPromiseRejectionWarning: Error: Generating schema error
[0]     at Function.<anonymous> (C:\Users\KeonS\Desktop\Programming\vinsmart-backend\node_modules\type-graphql\dist\schema\schema-generator.js:20:27)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (C:\Users\KeonS\Desktop\Programming\vinsmart-backend\node_modules\tslib\tslib.js:104:62)
[0]     at process._tickCallback (internal/process/next_tick.js:68:7)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
[0]     at startup (internal/bootstrap/node.js:283:19)
[0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[0] (node:9676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled
with .catch(). (rejection id: 1)
[0] (node:9676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by keonsam** [comment]
Fixed

**Comment by halfbeep** [comment]
what was the fix?

**Comment by tejas973** [comment]
@keonsam What was the fix ?

**Comment by keonsam** [comment]
I'm not too sure what the fix was. The problem may have come from fixing "no default export import express for 'express' " etc or using type-graphql resolves and mutation/query functions. What I did was start a new repo, don't fix the express problem, install graphql like what is on nest website, and only use type-graphql in the classes not in the resolvers, use @nest/graphql instead.

**Comment by keonsam** [comment]
The problem may have come from fixing the importing problem or your resolvers.
