### ISSUE TITLE
Internal error occurred during message handling. Please check your implementation. Error: Subscription field must return Async Iterable. Received: undefined.

### ISSUE THREAD

**Issue by imagine10255** [nestjs/graphql#2777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

show error
```
Internal error occurred during message handling. Please check your implementation. Error: Subscription field must return Async Iterable. Received: undefined.
    at createSourceEventStream (/Users/imagine/project/tempku/220618-api/node_modules/graphql/execution/subscribe.js:144:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at subscribe (/Users/imagine/project/tempku/220618-api/node_modules/graphql/execution/subscribe.js:57:26)
    at onMessage (/Users/imagine/project/tempku/220618-api/node_modules/@nestjs/graphql/node_modules/graphql-ws/lib/server.js:191:51)
    at WebSocket.<anonymous> (/Users/imagine/project/tempku/220618-api/node_modules/@nestjs/graphql/node_modules/graphql-ws/lib/use/ws.js:83:21)
```

<img width="367" alt="CleanShot 2023-04-18 at 22 43 17@2x" src="https://user-images.githubusercontent.com/5771353/232813135-fe612804-89bc-42c4-9165-708ee82552c9.png">

### Minimum reproduction code

https://github.com/imagine10255/nest-graphql-subscription-example

### Steps to reproduce

1. `yarn install`
2. `yarn dev`
3.  open http://localhost:8080/graphql
4. send request
```
subscription Pong {
  pong {
    id
    content
  }
}
```

sample code in `https://github.com/imagine10255/nest-graphql-subscription-example/blob/main/src/app/main/dashboard/resolvers/testsub.resolver.ts`

### Expected behavior

<img width="772" alt="CleanShot 2023-04-18 at 22 42 15@2x" src="https://user-images.githubusercontent.com/5771353/232812873-65d26557-1580-48f7-af43-72e23dfb460f.png">

### Package version

10.1.7

### Graphql version

`graphql`: 16.6.0
`apollo-server-express`: 3.11.1 

### NestJS version

9.1.6

### Node.js version

18.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by imagine10255** [comment]
The problem is solved, it is a low-level error, and the way of using the lowest code allows me to find the cause of the error.
In the method in APP_INTERCEPTOR, I only judged restfulRequest and graphqlRequest, and the others did not return, causing this error
