### ISSUE TITLE
Package including entity and resolver can't be loaded in GraphQL server

### ISSUE THREAD

**Issue by GeorgeHulpoi** [nestjs/graphql#2926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using a package is a great way to reusable code and maintenance it. Also, it's great because it can be used in theory in a monolithic project or be wrapped into a microservice. The problem is that when trying to do it, seems like the decorators are not propagating the types. For a basic reproduction, it throws the following error:

```
C:\Projects\test\node_modules\@nestjs\graphql\dist\schema-builder\factories\output-type.factory.js:19
                throw new cannot_determine_output_type_error_1.CannotDetermineOutputTypeError(hostType);
                      ^
Error: Cannot determine a GraphQL output type for the "id". Make sure your class is decorated with an appropriate decorator.
    at OutputTypeFactory.create (C:\Projects\test\node_modules\@nestjs\graphql\dist\schema-builder\factories\output-type.factory.js:19:23)
    at C:\Projects\test\node_modules\@nestjs\graphql\dist\schema-builder\factories\object-type-definition.factory.js:80:53
    at Array.forEach (<anonymous>)
    at C:\Projects\test\node_modules\@nestjs\graphql\dist\schema-builder\factories\object-type-definition.factory.js:79:24
    at resolveObjMapThunk (C:\Projects\test\node_modules\graphql\type\definition.js:504:40)
    at defineFieldMap (C:\Projects\test\node_modules\graphql\type\definition.js:766:20)
    at GraphQLObjectType._fields (C:\Projects\test\node_modules\graphql\type\definition.js:691:26)
    at GraphQLObjectType.getFields (C:\Projects\test\node_modules\graphql\type\definition.js:710:27)
    at collectReferencedTypes (C:\Projects\test\node_modules\graphql\type\schema.js:387:51)
    at new GraphQLSchema (C:\Projects\test\node_modules\graphql\type\schema.js:174:9)
```

### Minimum reproduction code

https://github.com/GeorgeHulpoi/nest-graphql-package-issue/tree/main

### Steps to reproduce

1. If needed, in `test-package` run `npm run clean` and then `npm run build`.
2. In `test` install the `test-package` via local path: `npm install /path/to/test-package`.
3. Run the `test`.

### Expected behavior

It should load the type and resolve and be available in GraphQL playground.

### Package version

12.0.7

### NestJS version

10.1.0

### Node.js version

v18.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
