### ISSUE TITLE
Always response Cannot return null for non-nullable field level2.level3 for nested resolver

### ISSUE THREAD

**Issue by twkevinzhang** [nestjs/graphql#3114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I need to make a nested request in 3 levels:
1. TodoItem
2. Comment
3. User(createdBy)

I use the "SDL First" approach, so I have a schema.graphql
```gql
type Query {
  todoItem(id: ID!): TodoItem
}

type TodoItem {
  id: ID!
  comments: [Comment!]!
}

type Comment {
  id: ID!
  todoItemID: ID!
  content: String!
  createdBy: User!
}

type User {
  uid: ID!
  username: String!
}
```

a file todo-item.resolver.ts
```ts
import { Resolver, Query, Args, ResolveField, Parent } from '@nestjs/graphql';
import { Comment, TodoItem, User } from 'src/graphql';

@Resolver('TodoItem')
export class TodoItemResolver {
  @Query()
  async todoItem(@Args('id') id: string): Promise<TodoItem> {
    return {
      id: 'todoItem1',
      comments: [],
    };
  }

  @ResolveField()
  async comments(@Parent() todoItem: TodoItem): Promise<Comment[]> {
    return [
      {
        id: 'comment1',
        todoItemID: 'todoItem1',
        content: 'i m comment1',
        createdBy: {} as User,
      },
    ];
  }
}

@Resolver('Comment')
export class CommentResolvers {
  @ResolveField()
  async createdBy(@Parent() comment: Comment): Promise<User> {
    return {
      uid: 'user1',
      username: 'user1',
    };
  }
}
```

and I query
```
query {
  todoItem(id: "1") {
    id
    comments {
      content
      createdBy {
        uid
        username
      }
    }
  }
}
```

I get an error.message
```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Comment.createdBy.",
      "locations": [
        {
          "line": 10,
          "column": 7
        }
      ],
      "path": [
        "todoItems",
        0,
        "comments",
        0,
        "createdBy"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Error: Cannot return null for non-nullable field Comment.createdBy.",
          "    at completeValue (/Users/.../node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/execute.js:605:13)",
          "    at executeField (/Users/.../node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/execute.js:500:19)",
          "    at executeFields (/Users/.../node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/execute.js:414:22)",
          "    at completeObjectValue (/Users/.../node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/execute.js:925:10)",
          "    at completeValue (/Users/.../node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/execute.js:646:12)",
          "    at completeValue (/Users/.../node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/execute.js:595:23)",
          "    at /Users/.../node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/execute.js:707:25",
          "    at Function.from (<anonymous>)",
          "    at completeListValue (/Users/.../node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/execute.js:687:34)",
          "    at completeValue (/Users/.../node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/execute.js:618:12)"
        ]
      }
    }
  ],
  "data": null
}
```

### Minimum reproduction code

https://gist.github.com/twkevinzhang/5dd8575718102ace95ca1affd0139224

### Steps to reproduce

1. npm i @nestjs/graphql @nestjs/apollo @apollo/server graphql
2. create schema.gql and todo-item.resolver.ts
3. add TodoItemResolver into AppModule
4. query `todoItem.comments.createdBy`

### Expected behavior

I expect to get
```json
{
  "data": {
    "todoItem": {
        "id": "todoItem1",
        "comments": [
            {
                "id": "comment1",
                "content": "i m comment",
                "createdByUID": "user1",
                "createdBy": {
                    "uid": "user1",
                    "username": "user`"
                }
            }
        ]
    }
  }
}
```

### Package version

12.0.11

### Graphql version

"@apollo/server": "^4.10.0",
"@nestjs/apollo": "^12.0.11",
"@nestjs/graphql": "^12.0.11",
"@nestjs/platform-express": "^10.0.0",
"graphql": "^16.8.1",
"reflect-metadata": "^0.1.13",
"rxjs": "^7.8.1",
"ts-morph": "^21.0.1"

### NestJS version

10.3.0

### Node.js version

20.9.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

what am I doing wrong?
I've already referenced:
 - https://stackoverflow.com/questions/71938904/how-to-create-multilevel-nested-queries-in-nestjs-graphql-using-resolvefield
 - https://github.com/nestjs/graphql/issues/475

but it didn't work.

**Comment by twkevinzhang** [comment]
Sorry everyone, I forgot to import CommentResolvers to app.module, now everything is fine.
