### ISSUE TITLE
Support Deno

### ISSUE THREAD

**Issue by stevefan1999-personal** [nestjs/graphql#3278]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to run NestJS with Deno and I can almost have the "zero node_modules" experience, but there is something wrong with module resolution.

Check out the repo here: https://github.com/stevefan1999-personal/nestjs-deno-test.
Current result for example (just run `deno task test`):
```
Task test deno test -A
Check file:///F:/deno/nestjs-graphql-bug-repro/test.ts
running 5 tests from ./test.ts
Normal hello world test ...
  expects to get hello world ... ok (1ms)
Normal hello world test ... ok (71ms)
Normal hello world test with express ...
  expects to get hello world ... ok (0ms)
Normal hello world test with express ... ok (3ms)
Normal hello world test with fastify ...
------- output -------
Not implemented: Server.setTimeout()
----- output end -----
  expects to get hello world ... ok (0ms)
Normal hello world test with fastify ... ok (24ms)
Normal GraphQL test with Apollo ... FAILED (5ms)
Normal GraphQL test with Mercurius ... FAILED (3ms)

 ERRORS 

Normal GraphQL test with Apollo => https://jsr.io/@std/testing/0.225.3/_test_suite.ts:194:10
error: Error: Nest can't resolve dependencies of the GraphQLModule (?, GqlModuleOptions, AbstractGraphQLDriver, GraphQLTypesLoader, GraphQLSchemaHost). Please make sure that the argument HttpAdapterHost at index [0] is available in the GraphQLModule context.

Potential solutions:
- Is GraphQLModule a valid NestJS module?
- If HttpAdapterHost is a provider, is it part of the current GraphQLModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within GraphQLModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })

    at TestingInjector.lookupComponentInParentModules (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:254:19)
    at async TestingInjector.resolveComponentInstance (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:207:33)
    at async TestingInjector.resolveComponentInstance (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/testing/10.3.10/testing-injector.js:19:45)
    at async resolveParam (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:128:38)
    at async Promise.all (index 0)
    at async TestingInjector.resolveConstructorParams (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:143:27)
    at async TestingInjector.loadInstance (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:70:13)
    at async TestingInjector.loadProvider (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:97:9)
    at async file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/instance-loader.js:56:13
    at async Promise.all (index 0)

Normal GraphQL test with Mercurius => https://jsr.io/@std/testing/0.225.3/_test_suite.ts:194:10
error: Error: Nest can't resolve dependencies of the GraphQLModule (?, GqlModuleOptions, AbstractGraphQLDriver, GraphQLTypesLoader, GraphQLSchemaHost). Please make sure that the argument HttpAdapterHost at index [0] is available in the GraphQLModule context.

Potential solutions:
- Is GraphQLModule a valid NestJS module?
- If HttpAdapterHost is a provider, is it part of the current GraphQLModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within GraphQLModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })

    at TestingInjector.lookupComponentInParentModules (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:254:19)
    at async TestingInjector.resolveComponentInstance (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:207:33)
    at async TestingInjector.resolveComponentInstance (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/testing/10.3.10/testing-injector.js:19:45)
    at async resolveParam (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:128:38)
    at async Promise.all (index 0)
    at async TestingInjector.resolveConstructorParams (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:143:27)
    at async TestingInjector.loadInstance (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:70:13)
    at async TestingInjector.loadProvider (file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/injector.js:97:9)
    at async file:///C:/Users/steve/AppData/Local/deno/npm/registry.npmjs.org/@nestjs/core/10.3.10_2/injector/instance-loader.js:56:13
    at async Promise.all (index 0)

 FAILURES 

Normal GraphQL test with Apollo => https://jsr.io/@std/testing/0.225.3/_test_suite.ts:194:10
Normal GraphQL test with Mercurius => https://jsr.io/@std/testing/0.225.3/_test_suite.ts:194:10

FAILED | 3 passed (3 steps) | 2 failed (113ms)

error: Test failed
```

### Describe the solution you'd like

Try to see why NestJS GraphQL support on Deno is broken

### What is the motivation / use case for changing the behavior?

Deno has everything NestJS needed.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
