### ISSUE TITLE
Specified query type "Query" not found in document with none graphql file.

### ISSUE THREAD

**Issue by dzzzzzy** [nestjs/graphql#39]
When I using the sample/12-graphql-apollo project, and I remove the graphql file, then run this project.

It throws some error:

```
(node:5278) UnhandledPromiseRejectionWarning: Error: Specified query type "Query" not found in document.
    at /home/dzzzzzy/workspace/nestjs/nest/sample/12-graphql-apollo/node_modules/graphql/utilities/buildASTSchema.js:133:17
    at Array.forEach (<anonymous>)
    at Object.buildASTSchema (/home/dzzzzzy/workspace/nestjs/nest/sample/12-graphql-apollo/node_modules/graphql/utilities/buildASTSchema.js:126:30)
    at buildSchemaFromTypeDefinitions (/home/dzzzzzy/workspace/nestjs/nest/sample/12-graphql-apollo/node_modules/graphql-tools/src/schemaGenerator.ts:225:32)
    at _generateSchema (/home/dzzzzzy/workspace/nestjs/nest/sample/12-graphql-apollo/node_modules/graphql-tools/src/schemaGenerator.ts:92:18)
    at Object.makeExecutableSchema (/home/dzzzzzy/workspace/nestjs/nest/sample/12-graphql-apollo/node_modules/graphql-tools/src/schemaGenerator.ts:120:20)
    at GraphQLFactory.createSchema (/home/dzzzzzy/workspace/nestjs/nest/sample/12-graphql-apollo/node_modules/@nestjs/graphql/dist/graphql.factory.js:23:32)
    at ApplicationModule.createSchema (/home/dzzzzzy/workspace/nestjs/nest/sample/12-graphql-apollo/src/app.module.ts:41:32)
    at ApplicationModule.configure (/home/dzzzzzy/workspace/nestjs/nest/sample/12-graphql-apollo/src/app.module.ts:24:25)
    at MiddlewareModule.loadConfiguration (/home/dzzzzzy/workspace/nestjs/nest/sample/12-graphql-apollo/node_modules/@nestjs/core/middleware/middleware-module.js:35:18)
(node:5278) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5278) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When `console.log(typeDefs)` with none graphql file at other projects, it always throw this error and console shows:

```
schema {
  query: Query
}
```

**Comment by kamilmysliwiec** [comment]
Could you provide a repository that reproduces your issue?

**Comment by antontemchenko** [comment]
Same here:
`(node:1646) UnhandledPromiseRejectionWarning: Error: Specified query type "Query" not found in document.
    at getOperationTypes (/Users/antontemchenko/Projects/Skillz/nest/node_modules/graphql/utilities/buildASTSchema.js:157:17)
    at Object.buildASTSchema (/Users/antontemchenko/Projects/nest/node_modules/graphql/utilities/buildASTSchema.js:94:36)
    at Object.buildSchemaFromTypeDefinitions (/Users/antontemchenko/Projects/nest/node_modules/graphql-tools/src/generate/buildSchemaFromTypeDefinitions.ts:43:32)
    at Object.makeExecutableSchema (/Users/antontemchenko/Projects/nest/node_modules/graphql-tools/src/makeExecutableSchema.ts:52:18)
    at GraphQLFactory.<anonymous> (/Users/antontemchenko/Projects/nest/node_modules/@nestjs/graphql/dist/graphql.factory.js:43:62)
    at Generator.next (<anonymous>)
    at /Users/antontemchenko/Projects/nest/node_modules/@nestjs/graphql/dist/graphql.factory.js:16:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/antontemchenko/Projects/nest/node_modules/@nestjs/graphql/dist/graphql.factory.js:12:12)
    at GraphQLFactory.mergeOptions (/Users/antontemchenko/Projects/nest/node_modules/@nestjs/graphql/dist/graphql.factory.js:36:16)
(node:1646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1646) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by antontemchenko** [comment]
Steps to reproduce:
in new nestjs project follow [graphql quickstart](https://docs.nestjs.com/graphql/quick-start):

1. `npm i --save @nestjs/graphql apollo-server-express graphql-tools graphql`
2. Import GraphQLModule
3. Start  an application (prod / dev)
4. Observe an error.

**Comment by davidlav** [comment]
I get the exact same error as well trying to follow the official tutorial at https://docs.nestjs.com/graphql/quick-start

**Comment by kamilmysliwiec** [comment]
Ensure to update `@nestjs/graphql` to latest version.

**Comment by davidlav** [comment]
I'm using version 5.2.2 of @nestjs/graphql and am still getting the same error as @antontemchenko by following the same four steps in the GraphQL quick start.

**Comment by davidlav** [comment]
@kamilmysliwiec I think I figured it out, the problem is with the quick start tutorial itself, not the library.  If I download and run the example here (https://github.com/nestjs/nest/tree/master/sample/12-graphql-apollo), it works perfectly.  If I delete the cats.graphql file, I get the exact same error as above (`Specified query type "Query" not found in document.`).

I believe the quick start example is broken because it doesn't have you create a .graphql file.

**Comment by kamilmysliwiec** [comment]
Just pushed 5.2.3 temporary fix. The issue comes from the underlying lib: https://github.com/okgrow/merge-graphql-schemas/issues/155

**Comment by davidlav** [comment]
Thanks!

**Comment by davidlav** [comment]
Thanks! Was beating my head against the wall last night wondering why the playgound was having server connection errors.
