### ISSUE TITLE
Validation error messages inconsistent/wrong when using remote schema stitching.

### ISSUE THREAD

**Issue by InterStelios** [nestjs/graphql#423]
## I'm submitting a...
[x] Bug report

## Current behavior

When using remote schema stitching using the `makeRemoteExecutableSchema` function from the `graphql-tools` package, the validation errors (via decorators) are not displayed properly. Here's an example response from the validation error: 

```
{
  "errors": [
    {
      "message": "[object Object]",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "errors": [
            {
              "message": {
                "statusCode": 400,
                "error": "Bad Request",
                "message": [
                  {
                    "target": {
                      "email": "hello@nest.js",
                      "password": "short"
                    },
                    "value": "short",
                    "property": "password",
                    "children": [],
                    "constraints": {
                      "matches": "password must match /^(?=.*[a-z])(?=.*[A-Z])(?=.{8,}).*/ regular expression"
                    }
                  }
                ]
              },
              "locations": [],
              "path": [
                "login"
              ]
            }
          ],
          "stacktrace": [
            "Error: [object Object]",
            "    at new CombinedError (/Users/sk/Shell/code/nexus-solutions-hub-graphql/node_modules/graphql-tools/dist/stitching/errors.js:82:28)",
            "    at Object.checkResultAndHandleErrors (/Users/sk/Shell/code/nexus-solutions-hub-graphql/node_modules/graphql-tools/dist/stitching/errors.js:98:15)",
            "    at CheckResultAndHandleErrors.transformResult (/Users/sk/Shell/code/nexus-solutions-hub-graphql/node_modules/graphql-tools/dist/transforms/CheckResultAndHandleErrors.js:9:25)",
            "    at /Users/sk/Shell/code/nexus-solutions-hub-graphql/node_modules/graphql-tools/dist/transforms/transforms.js:18:54",
            "    at Array.reduce (<anonymous>)",
            "    at applyResultTransforms (/Users/sk/Shell/code/nexus-solutions-hub-graphql/node_modules/graphql-tools/dist/transforms/transforms.js:17:23)",
            "    at /Users/sk/Shell/code/nexus-solutions-hub-graphql/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:97:50",
            "    at step (/Users/sk/Shell/code/nexus-solutions-hub-graphql/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:31:23)",
            "    at Object.next (/Users/sk/Shell/code/nexus-solutions-hub-graphql/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:53)",
            "    at fulfilled (/Users/sk/Shell/code/nexus-solutions-hub-graphql/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:3:58)"
          ]
        }
      }
    }
  ],
  "data": null,
  "extensions": {
    "cacheControl": {
      "version": 1,
      "hints": [
        {
          "path": [
            "login"
          ],
          "maxAge": 0
        }
      ]
    }
  }
}
```
_Note that the above example is using the `login` mutation that is defined in the "host" schema and not in the remote._ 

Without changing anything else but simply removing the remote schema stitching the exact same mutation returns:

```
{
  "errors": [
    {
      "message": {
        "statusCode": 400,
        "error": "Bad Request",
        "message": [
          {
            "target": {
              "email": "hello@nest.js",
              "password": "short"
            },
            "value": "short",
            "property": "password",
            "children": [],
            "constraints": {
              "matches": "password must match /^(?=.*[a-z])(?=.*[A-Z])(?=.{8,}).*/ regular expression"
            }
          }
        ]
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "response": {
            "statusCode": 400,
            "error": "Bad Request",
            "message": [
              {
                "target": {
                  "email": "hello@nest.js",
                  "password": "short"
                },
                "value": "short",
                "property": "password",
                "children": [],
                "constraints": {
                  "matches": "password must match /^(?=.*[a-z])(?=.*[A-Z])(?=.{8,}).*/ regular expression"
                }
              }
            ]
          },
          "status": 400,
          "message": {
            "statusCode": 400,
            "error": "Bad Request",
            "message": [
              {
                "target": {
                  "email": "hello@nest.js",
                  "password": "short"
                },
                "value": "short",
                "property": "password",
                "children": [],
                "constraints": {
                  "matches": "password must match /^(?=.*[a-z])(?=.*[A-Z])(?=.{8,}).*/ regular expression"
                }
              }
            ]
          },
          "stacktrace": [
            "Error: [object Object]",
            "    at ValidationPipe.exceptionFactory.options.exceptionFactory.errors [as exceptionFactory] (/Users/sk/Shell/code/nexus-solutions-hub-graphql/node_modules/@nestjs/common/pipes/validation.pipe.js:44:28)",
            "    at ValidationPipe.transform (/Users/sk/Shell/code/nexus-solutions-hub-graphql/node_modules/@nestjs/common/pipes/validation.pipe.js:61:24)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": null,
  "extensions": {
    "cacheControl": {
      "version": 1,
      "hints": [
        {
          "path": [
            "login"
          ],
          "maxAge": 0
        }
      ]
    }
  }
}
``` 

## Expected behavior
The expected behaviour is that in both cases, the standard error response should be returned

## Minimal reproduction of the problem with instructions
1. Checkout `git@github.com:InterStelios/nest-stitching-validation-error-message-bug.git`
2. Run the project and execute the following mutation:
```
mutation {
  addRecipe(
    newRecipeData: { title: "1", description: "1", ingredients: [""] }
  ) {
    id
  }
}
```

**You will see that the validation error message is incorrect.** 

3. Comment out `transformSchema` property in `app.module`. 

**Run the same mutation; you will see that the error message is now correct.**

## Environment
See versions in the `package.json` example repo.
 
For Tooling issues:
- Node version: v10.14.1
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Let's track this issue here https://github.com/nestjs/nest/pull/3053

**Comment by marcus-sa** [comment]
Schema stitching is deprecated in favor of Apollo Federation btw
