### ISSUE TITLE
Incorrect type for `typeDefs` in GqlModuleOptions

### ISSUE THREAD

**Issue by michaelbromley** [nestjs/graphql#53]
## I'm submitting a...
<pre><code>
[ x ] Bug report
</code></pre>

## Current behavior
In the interface `GqlModuleOptions`, the `typeDefs` property is inherited from the apollo-server `Config` interface, which defines it as `typeDefs?: DocumentNode | Array<DocumentNode>;`

However, when I pass a DocumentNode as the value of `typeDefs`, I get the following error:

```
[Nest] 15752   - 2018-9-3 16:43:12   [ExceptionHandler] Syntax Error: Unexpected [ +102ms
Syntax Error: Unexpected [

GraphQL request (5:2)
4: }
5: ,[object Object]
    ^
6:         

    at syntaxError (C:\Development\vendure\vendure\server\node_modules\graphql\error\syntaxError.js:24:10)
    at unexpected (C:\Development\vendure\vendure\server\node_modules\graphql\language\parser.js:1485:33)
    at parseDefinition (C:\Development\vendure\vendure\server\node_modules\graphql\language\parser.js:160:9)
    at parseDocument (C:\Development\vendure\vendure\server\node_modules\graphql\language\parser.js:115:22)
    at parse (C:\Development\vendure\vendure\server\node_modules\graphql\language\parser.js:48:10)
    at parseDocument (C:\Development\vendure\vendure\server\node_modules\graphql-tag\src\index.js:129:16)
    at Object.gql (C:\Development\vendure\vendure\server\node_modules\graphql-tag\src\index.js:170:10)
    at GraphQLFactory.mergeOptions (C:\Development\vendure\vendure\server\node_modules\@nestjs\graphql\dist\graphql.factory.js:32:55)
    at Function.<anonymous> (C:\Development\vendure\vendure\server\node_modules\@nestjs\graphql\dist\graphql.module.js:73:55)
    at Generator.next (<anonymous>)
```

Passing a string representation of the schema on the other hand works, but then I need to cast the string to `any` to avoid type errors.

This line in the `GraphQLFactory` class seems to be the point that the value is used as a string (or array of strings to be exact):
https://github.com/nestjs/graphql/blob/b58d3e50dc9672a1047ef192587849fbbfc42281/lib/graphql.factory.ts#L32-L34

## Expected behavior
Either the GraphQLFactory should perform a check to see if the `typeDefs` is a DocumentNode, and if so then skip the `gql` tag call.

Or just change the `GqlModuleOptions` to make typeDefs a string type.

## Environment

<pre><code>
Nest version: 5.3.0, graphql v5.1.0
</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in v5.1.1. Thanks for reporting
